openapi: "3.0.0"
info:
  title: Recipe Management API
  description: A RESTful API for managing favorite recipes
  version: "1.0.0"

servers:
  - url: http://localhost:8080/api/v1

tags:
  - name: Recipe

paths:
  /recipe-manager/api/v1/search/recipes:
    get:
      summary: Get all recipes by category
      description: Retrieve a list of all recipes by category
      operationId: getRecipesByCategory
      tags:
        - searchRecipe
      parameters:
        - in: query
          name: isVeg
          description: filters all the recipes based on isVeg option
          required: false
          schema:
            type: boolean
        - in: query
          name: serving
          description: filters all the recipes based on number of servings
          required: false
          schema:
            type: integer
        - in: query
          name: includedIngredients
          description: filters all the recipes based on number of servings
          required: false
          schema:
            type: array
            items:
              type: string
        - in: query
          name: excludedIngredients
          description: filters all the recipes based on number of servings
          required: false
          schema:
            type: array
            items:
              type: string
        - in: query
          name: searchInstructions
          description: filters all the recipes based on number of servings
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
components:
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        isVegetarian:
          type: boolean
        servings:
          type: integer
        ingredients:
          type: array
          items:
            type: string
        instructions:
          type: string
      required:
        - name
        - isVegetarian
        - servings
        - ingredients
        - instructions